Repository TogetherHana/Frontend, pull requests merged in 2024-07, with the labels that each got.

#26 feat/baseball_sharing_account
  package-lock.json
  package.json
  src/assets/images/punch.svg
  src/layouts/index.js
  src/pages/BaseballMeetingAccount/baseball_home.jsx
  src/pages/BaseballMeetingAccount/baseball_home.scss
  src/pages/BaseballMeetingAccount/bigmatch_history.jsx
  src/pages/BaseballMeetingAccount/bigmatch_history.scss
  src/pages/BaseballMeetingAccount/friends.jsx
  src/pages/BaseballMeetingAccount/friends.scss
  src/pages/BaseballMeetingAccount/history.jsx
  src/pages/BaseballMeetingAccount/history.scss
  src/pages/BigMatch/create.jsx
  src/pages/BigMatch/create.scss
  src/pages/index.js
  src/routes/index.jsx
Labels: feat🚀, 고은🐨

#33 feat/bigmatch api
  src/pages/BaseballMeetingAccount/baseball_home.jsx
  src/pages/BaseballMeetingAccount/bigmatch_history.jsx
  src/pages/BaseballMeetingAccount/bigmatch_history.scss
  src/pages/BaseballMeetingAccount/history.jsx
  src/pages/BaseballMeetingAccount/history.scss
  src/pages/BigMatch/create.jsx
  src/pages/BigMatch/finish.jsx
  src/pages/BigMatch/finish.scss
  src/pages/BigMatch/index.jsx
  src/pages/BigMatch/style.scss
  src/pages/BigMatch/voted.jsx
  src/pages/BigMatch/voted.scss
  src/pages/SendingFee/fee_input.jsx
  src/pages/SendingFee/fee_input.scss
  src/pages/SendingFee/fee_send.jsx
  src/pages/SendingFee/fee_send.scss
  src/pages/index.js
  src/routes/index.jsx
Labels: feat🚀, 고은🐨

#32 feat/apply-responsive-style-1
  package-lock.json
  package.json
  src/common/styles/scss/responsive.scss
  src/components/Button/style.scss
  src/components/Cheering/sportstype.jsx
  src/components/Cheering/teamlogo.jsx
  src/components/JoinPlatform/bankdetail.jsx
  src/components/JoinPlatform/dialog1.jsx
  src/components/JoinPlatform/styles.scss
  src/components/Main/styles.scss
  src/components/MeetingAccount/AgreeTerms/bottompopupinfo.jsx
  src/components/MeetingAccount/AgreeTerms/style.scss
  src/components/MeetingAccount/Register/register.scss
  src/components/MeetingAccount/Register/register1.jsx
  src/components/MeetingAccount/Register/registerbtn.jsx
  src/components/MeetingAccount/SelectStock/stockdiv.jsx
  src/components/MeetingAccount/SetAccountInfo/infohalfbtn.jsx
  src/components/MeetingAccount/SetAccountInfo/numberkeypad.jsx
  src/components/MeetingAccount/SetAccountInfo/style.scss
  src/components/Mileage/mileage-product-category.jsx
  src/components/Mileage/mileage-product-div.jsx
  src/pages/Cheering/baseball_index.jsx
  src/pages/Cheering/baseball_style.scss
  src/pages/Cheering/index.jsx
  src/pages/Cheering/style.scss
  src/pages/Home/index.jsx
  src/pages/Home/style.scss
  src/pages/JoinPlatform/join-account-authentication.jsx
  src/pages/JoinPlatform/join-account-link.jsx
  src/pages/JoinPlatform/join-id-verification.jsx
  src/pages/JoinPlatform/join-intro.jsx
  src/pages/JoinPlatform/join-main.jsx
  src/pages/JoinPlatform/joinintro.jsx
  src/pages/JoinPlatform/joinmain.jsx
  src/pages/JoinPlatform/styles.scss
  src/pages/MeetingAccount/InviteCode/mac-ic-agree-terms.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-bottom-popupinfo.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-complete.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-main.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-registering.jsx
  src/pages/MeetingAccount/InviteCode/style.scss
  src/pages/MeetingAccount/Register/mac-agree-terms.jsx
  src/pages/MeetingAccount/Register/mac-complete.jsx
  src/pages/MeetingAccount/Register/mac-createdinfo.jsx
  src/pages/MeetingAccount/Register/mac-id-verification.jsx
  src/pages/MeetingAccount/Register/mac-register.jsx
  src/pages/MeetingAccount/Register/mac-select-stock.jsx
  src/pages/MeetingAccount/Register/mac-set-account-name.jsx
  src/pages/MeetingAccount/Register/mac-set-account-pw.jsx
  src/pages/MeetingAccount/Register/mac-userinfo.jsx
  src/pages/MeetingAccount/Register/style.scss
  src/pages/MeetingAccount/style.scss
  src/pages/Mileage/index.jsx
  src/pages/Mileage/style.scss
  src/pages/SystemEvent/se-select-win.jsx
  src/pages/SystemEvent/se-select-winb.jsx
  src/pages/SystemEvent/style.scss
  src/pages/index.js
  src/routes/index.jsx
Labels: feat🚀, 상민🐼

#36 fix/pages-index
  src/pages/Main/index.jsx
  src/pages/Main/style.scss
  src/pages/index.js
  src/routes/index.jsx
Labels: fix🚧, 상민🐼

#37 fix/error resolve
  src/pages/Main/index.jsx
  src/pages/Main/style.scss
  vercel.json
Labels: fix🚧, 상민🐼

#38 feat/platform-register-api
  index.html
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  public/service-worker.js
  src/assets/images/hana7070.svg
  src/assets/images/joinmembership/infocheckcard.svg
  src/assets/images/meetaccountinfo/pwbaseball.svg
  src/assets/images/meetaccountinfo/pwbasketball.svg
  src/assets/images/meetaccountinfo/pwfootball.svg
  src/assets/images/meetaccountinfo/pwvolleyball.svg
  src/common/styles/scss/base.scss
  src/components/JoinPlatform/authcheck-modalcontent.jsx
  src/components/JoinPlatform/bankdetail.jsx
  src/components/Main/mainaccountlastdiv.jsx
  src/components/MeetingAccount/SelectStock/stockdiv.jsx
  src/components/MeetingAccount/SetAccountInfo/maskingpwarea.jsx
  src/components/MeetingAccount/SetAccountInfo/style.scss
  src/components/Modal/authenticationmodal.jsx
  src/components/Modal/style.scss
  src/firebase-messaging-sw.js
  src/firebase.js
  src/main.jsx
  src/pages/JoinPlatform/join-account-link.jsx
  src/pages/JoinPlatform/join-id-verification.jsx
  src/pages/JoinPlatform/join-info-check.jsx
  src/pages/JoinPlatform/join-intro.jsx
  src/pages/JoinPlatform/join-notification-request.jsx
  src/pages/JoinPlatform/join-register-processing.jsx
  src/pages/JoinPlatform/joinauthenticationcheck.jsx
  src/pages/JoinPlatform/joinsetnickname.jsx
  src/pages/JoinPlatform/styles.scss
  src/pages/Main/index.jsx
  src/pages/Main/style.scss
  src/pages/MeetingAccount/Register/mac-complete.jsx
  src/pages/MeetingAccount/Register/mac-createdinfo.jsx
  src/pages/MeetingAccount/Register/mac-id-verification.jsx
  src/pages/MeetingAccount/Register/mac-select-stock.jsx
  src/pages/MeetingAccount/Register/mac-set-account-name.jsx
  src/pages/MeetingAccount/Register/mac-set-account-pw-check.jsx
  src/pages/MeetingAccount/Register/mac-set-account-pw.jsx
  src/pages/MeetingAccount/Register/mac-userinfo.jsx
  src/pages/MeetingAccount/Register/style.scss
  src/pages/index.js
  src/register-sw.jsx
  src/routes/index.jsx
  src/serviceWorker.js
  src/setup_proxy.jsx
  src/stores/index.js
Labels: feat🚀, 상민🐼

#43 feat/home userinfo api link
  public/service-worker.js
  src/components/Main/mainaccountdiv.jsx
  src/pages/Home/index.jsx
  src/pages/Main/index.jsx
Labels: feat🚀, 상민🐼

#44 feat/create mac api complete
  src/App.jsx
  src/components/MeetingAccount/AgreeTerms/termsdiv.jsx
  src/components/MeetingAccount/IdVerification/verificationbtn.jsx
  src/pages/Home/index.jsx
  src/pages/MeetingAccount/Register/mac-agree-terms.jsx
  src/pages/MeetingAccount/Register/mac-createdinfo.jsx
  src/pages/MeetingAccount/Register/mac-register-processing.jsx
  src/pages/MeetingAccount/Register/mac-userinfo.jsx
  src/pages/MeetingAccount/Register/style.scss
  src/pages/index.js
  src/routes/index.jsx
  src/stores/index.js
Labels: feat🚀, 상민🐼

#46 feat/transfer_money
  src/components/Main/mainaccountdiv.jsx
  src/components/Modal/sendFeeCheckmodal.jsx
  src/components/Modal/style.scss
  src/layouts/NonFooter/green_style.scss
  src/pages/BaseballMeetingAccount/baseball_home.jsx
  src/pages/BaseballMeetingAccount/baseball_home.scss
  src/pages/BaseballMeetingAccount/friends.jsx
  src/pages/BaseballMeetingAccount/history.jsx
  src/pages/BaseballMeetingAccount/history.scss
  src/pages/BigMatch/create.jsx
  src/pages/Cheering/style.scss
  src/pages/CollectingFee/fee_collect.jsx
  src/pages/CollectingFee/fee_collect.scss
  src/pages/CollectingFee/fee_input.jsx
  src/pages/CollectingFee/fee_input.scss
  src/pages/SendingFee/fee_input.jsx
  src/pages/SendingFee/fee_input.scss
  src/pages/SendingFee/fee_send.jsx
  src/pages/SendingFee/fee_send.scss
  src/pages/SendingFee/pw_check.jsx
  src/pages/SendingFee/style.scss
  src/pages/index.js
  src/routes/index.jsx
  src/stores/index.js
Labels: feat🚀, 고은🐨

#49 feat/mac invitecode link
  src/App.jsx
  src/assets/images/meetaccountic/completedialog.svg
  src/components/Button/homeaccountdivbtn.jsx
  src/components/Main/mainaccountdiv.jsx
  src/components/Main/mainaccountlink.jsx
  src/layouts/Footer/gray_footer.jsx
  src/layouts/Footer/green_footer.jsx
  src/layouts/Footer/white_footer.jsx
  src/pages/Home/home-data-processing.jsx
  src/pages/Home/index.jsx
  src/pages/Home/style.scss
  src/pages/JoinPlatform/join-authentication-check.jsx
  src/pages/JoinPlatform/join-complete.jsx
  src/pages/JoinPlatform/join-info-check.jsx
  src/pages/JoinPlatform/join-set-nickname.jsx
  src/pages/JoinPlatform/styles.scss
  src/pages/Main/index.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-agree-terms.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-complete.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-main.jsx
  src/pages/MeetingAccount/InviteCode/mac-ic-registering.jsx
  src/pages/MeetingAccount/InviteCode/style.scss
  src/pages/index.js
  src/routes/index.jsx
  src/stores/index.js
Labels: feat🚀, 상민🐼

#48 feat/firstComeEvent
  src/assets/images/firstComeEvent/fail.svg
  src/assets/images/firstComeEvent/firstComeEventBackGround.svg
  src/assets/images/firstComeEvent/firstComeEventBanner.svg
  src/assets/images/firstComeEvent/success.svg
  src/assets/images/firstComeEvent/ticket.svg
  src/pages/FirstComeEvent/play.jsx
  src/pages/FirstComeEvent/play.scss
  src/pages/FirstComeEvent/waitingRoom.jsx
  src/pages/FirstComeEvent/waitingRoom.scss
  src/pages/index.js
  src/routes/index.jsx
Labels: feat🚀, 지연😽

#51 fix/token
  src/common/styles/scss/responsive.scss
  src/components/Main/mainaccountdiv.jsx
  src/pages/BaseballMeetingAccount/baseball_home.jsx
  src/pages/BaseballMeetingAccount/bigmatch_history.jsx
  src/pages/BaseballMeetingAccount/bigmatch_history.scss
  src/pages/BaseballMeetingAccount/friends.jsx
  src/pages/BaseballMeetingAccount/friends.scss
  src/pages/BaseballMeetingAccount/history.jsx
  src/pages/BigMatch/create.jsx
  src/pages/BigMatch/index.jsx
  src/pages/BigMatch/voted.jsx
  src/pages/CollectingFee/fee_collect.jsx
  src/pages/CollectingFee/fee_collect.scss
  src/pages/CollectingFee/fee_input.scss
  src/pages/FirstComeEvent/play.jsx
  src/pages/Home/index.jsx
  src/pages/SendingFee/fee_send.jsx
  src/pages/SendingFee/pw_check.jsx
  src/stores/index.js
Labels: fix🚧, refactor💎, 고은🐨

#54 관리자페이지
  package-lock.json
  package.json
  src/components/Button/GradientButton.jsx
  src/components/Card/CardWithButton.jsx
  src/components/Card/CountingCard.jsx
  src/components/Chart/BarChart.jsx
  src/components/Chart/LineChart.jsx
  src/components/Rating/StarAndLink.jsx
  src/layouts/Admin/AdminFooter.jsx
  src/layouts/Admin/AdminLayout.jsx
  src/layouts/Admin/AdminSidebar.jsx
  src/layouts/index.js
  src/pages/Admin/EventStatistics.jsx
  src/pages/Admin/TransferStatistics.jsx
  src/pages/index.js
  src/routes/index.jsx
Labels: feat🚀, 지후🦖

#56 feat/admin_stats
  src/components/Card/CountingCard.jsx
  src/components/Chart/BarChart.jsx
  src/layouts/Admin/AdminLayout.jsx
  src/layouts/Admin/AdminSidebar.jsx
  src/pages/Admin/TransferStatistics.jsx
  src/routes/index.jsx
Labels: feat🚀, 고은🐯

#58 feat/add certification display
  src/pages/MeetingAccount/Register/mac-createdinfo.jsx
  src/pages/MeetingAccount/Register/mac-id-certification.jsx
  src/pages/MeetingAccount/Register/mac-id-verification.jsx
  src/pages/MeetingAccount/Register/mac-register-processing.jsx
  src/pages/MeetingAccount/Register/mac-select-stock.jsx
  src/pages/MeetingAccount/Register/mac-set-account-pw-check.jsx
  src/pages/MeetingAccount/Register/mac-set-account-pw.jsx
  src/pages/MeetingAccount/Register/style.scss
  src/pages/index.js
  src/routes/index.jsx
  vite.config.js
Labels: feat🚀, 상민🐼

#59 Feat/admin/#53
  src/components/Chart/BarChart.jsx
  src/components/Chart/LineChart.jsx
  src/layouts/Admin/AdminFooter.jsx
  src/layouts/Admin/AdminLayout.jsx
  src/layouts/Admin/AdminSidebar.jsx
  src/pages/Admin/EventStatistics.jsx
  src/pages/Admin/TransferStatistics.jsx
Labels: feat🚀, 지후🦖

#60 fix/features
  src/common/styles/scss/responsive.scss
  src/pages/BaseballMeetingAccount/baseball_home.scss
  src/pages/BaseballMeetingAccount/bigmatch_history.scss
  src/pages/BaseballMeetingAccount/friends.scss
  src/pages/BaseballMeetingAccount/history.scss
  src/pages/BigMatch/create.scss
  src/pages/BigMatch/finish.scss
  src/pages/BigMatch/style.scss
  src/pages/Cheering/baseball_style.scss
  src/pages/Cheering/style.scss
  src/pages/CollectingFee/fee_collect.scss
  src/pages/CollectingFee/fee_input.scss
  src/pages/SendingFee/fee_input.scss
  src/pages/SendingFee/fee_send.scss
  src/pages/SendingFee/style.scss
  src/routes/index.jsx
Labels: fix🚧, refactor💎, 고은🐯

#61 fix/features
  src/components/Cheering/teamlogo.jsx
  src/pages/BigMatch/finish.jsx
  src/pages/BigMatch/index.jsx
  src/pages/BigMatch/voted.jsx
  src/pages/Cheering/index.jsx
  src/pages/CollectingFee/fee_collect.jsx
  src/pages/SendingFee/pw_check.jsx
Labels: fix🚧, 고은🐯

#62 fix/features
  src/components/Cheering/teamlogo.jsx
  src/pages/BaseballMeetingAccount/baseball_home.jsx
Labels: fix🚧, 고은🐯

#63 fix/features
  src/pages/BigMatch/index.jsx
Labels: fix🚧, 고은🐯

#64 fix/features
  src/components/Main/mainaccountdiv.jsx
  src/pages/BaseballMeetingAccount/friends.scss
Labels: fix🚧, 고은🐯

#65 fix/features
  src/pages/CollectingFee/fee_input.scss
Labels: fix🚧, 고은🐯

#66 fix/features
  src/components/MeetingAccount/IdVerification/verificationbtn.jsx
  src/pages/MeetingAccount/Register/mac-id-certification.jsx
Labels: fix🚧, 고은🐯
